# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
## https://github.com/edzer/sfr/issues/142

language: R
sudo: required

# https://github.com/ropensci/rgbif/blob/master/.travis.yml#L9
dist: trusty

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

after_success:
  - Rscript -e 'covr::codecov()'

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
